package com.unison.binku.ViewModels

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.*
import com.unison.binku.Models.ModeloPost

class FeedViewModel : ViewModel() {

    private val _posts = MutableLiveData<ArrayList<ModeloPost>>(arrayListOf())
    val posts: LiveData<ArrayList<ModeloPost>> get() = _posts

    // Firebase reference to the "Posts" node
    private val databaseReference = FirebaseDatabase.getInstance().getReference("Posts")
    private val firebaseAuth = FirebaseAuth.getInstance()

    private val postListener = object : ValueEventListener {
        override fun onDataChange(snapshot: DataSnapshot) {
            val tempList = ArrayList<ModeloPost>()
            for (ds in snapshot.children) {
                try {
                    val post = ds.getValue(ModeloPost::class.java)
                    post?.postId = ds.key ?: "" // Capture the unique ID from Firebase
                    if (post != null) {
                        tempList.add(post)
                    }
                } catch (e: Exception) {
                    // Log error or handle cases where data structure might be wrong
                    // Log.e("FeedViewModel", "Error converting post", e)
                }
            }
            tempList.reverse() // Show newest posts first
            _posts.value = tempList
        }

        override fun onCancelled(error: DatabaseError) {
            // Handle error, maybe post an empty list or an error state
            // Log.e("FeedViewModel", "Firebase read error: ${error.message}")
            _posts.value = arrayListOf()
        }
    }

    init {
        cargarPostsDesdeFirebase()
    }

    // Function called from FragmentFeed to add a new post
    fun agregarPostFirebase(postText: String, imageUriString: String?) {
        val currentUser = firebaseAuth.currentUser ?: return // Need logged-in user

        val nuevoPost = ModeloPost(
            // postId will be generated by push()
            uidAutor = currentUser.uid,
            nombreAutor = currentUser.displayName ?: "Usuario Binku", // Use display name
            textoPost = postText,
            imagenUrlPost = imageUriString ?: "", // Initially, store local URI or empty string
            timestamp = System.currentTimeMillis()
        )

        // Generate unique ID and save to Firebase
        val postId = databaseReference.push().key
        if (postId != null) {
            databaseReference.child(postId).setValue(nuevoPost)
                .addOnSuccessListener {
                    // Success! Listener will automatically update the list.
                }
                .addOnFailureListener {
                    // Handle error, maybe show a Toast to the user
                }
        }
    }

    private fun cargarPostsDesdeFirebase() {
        // Listen for real-time updates on the "Posts" node
        databaseReference.addValueEventListener(postListener)
    }

    override fun onCleared() {
        super.onCleared()
        // Stop listening when the ViewModel is destroyed
        databaseReference.removeEventListener(postListener)
    }
}